sudo: required

branches:
  only:
    - develop

services:
  - docker

language: bash

before_install:
  - docker build -t dertin/debian:lemp -f Dockerfile.debug .
  - docker run -t --name container_test dertin/debian:lemp /bin/bash -c "uname -a"
  - docker exec -t container_test /bin/bash -c "/root/workspace/install.sh travis Y"
  - docker start container_test
  - docker ps -a

# Test
script:
  - docker exec -t container_test /bin/bash -c "php -v"

#after_success:
#after_failure:

after_script:
  - docker stop container_test
  - docker rm $(docker ps -a -q)

notifications:
  email: false
