sudo: required

branches:
  only:
    - develop

services:
  - docker

language: bash

before_install:
- docker build -t dertin/debian:lemp -f Dockerfile.debug .
- docker run -t dertin/debian:lemp /bin/bash -c "/root/workspace/travis-test.sh"

# Test
script:
  - wget -V

#after_success:
#after_failure:
#after_script:

notifications:
  email: false
